#!/usr/bin/env ruby

if ARGV.include?('-d')
  require 'rubygems'
  ARGV.delete('-d')
  ARGV.unshift('start') unless ARGV.detect{|a| ['start', 'restart'].include?(a)}

  root = File.expand_path(File.dirname(__FILE__) + '/..')
  ARGV << "--rails=#{root}"

  version = ">= 0"

  if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
    version = $1
    ARGV.shift
  end

  gem 'sweatshop', version
  system("#{Gem.bin_path('sweatshop', 'sweatd', version)} #{ARGV.join(' ')}")
  exit $?.exitstatus
else
  puts "Loading Rails..."
  require File.dirname(__FILE__) + '/../config/environment'
  puts "Listening for new tasks..."
  Sweatshop.do_all_tasks
end
